### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by tvasenin** [MonoS/VS-ContinuityFixer#2]
Please, release new version -- recent namespace (and other) changes are important, especially since they are used by https://github.com/JustinTArthur/vsfieldkit .

**Comment by MonoS** [comment]
Hi tvasenin, i don't understand why you want this version updated when [sekrit-twc/EdgeFixer](https://github.com/sekrit-twc/EdgeFixer) exists.
If you need a version that can fix all planes in a single call you can use this code
```
def ContinuityFixer(src, left=[0,0,0], top=[0,0,0], right=[0,0,0], bottom=[0,0,0], radius=[0,0,0]):
	core = vs.core
	
	Y = core.std.ShufflePlanes(src, [0], vs.GRAY)
	U = core.std.ShufflePlanes(src, [1], vs.GRAY)
	V = core.std.ShufflePlanes(src, [2], vs.GRAY)
	
	if (left[0] + top[0] + right[0] + bottom[0] > 0):
		Yfix = core.edgefixer.Continuity(Y, left[0], top[0], right[0], bottom[0], radius[0])
		
	if (left[1] + top[1] + right[1] + bottom[1] > 0):
		Ufix = core.edgefixer.Continuity(U, left[1], top[1], right[1], bottom[1], radius[1])
	
	if (left[2] + top[2] + right[2] + bottom[2] > 0):
		Vfix = core.edgefixer.Continuity(V, left[2], top[2], right[2], bottom[2], radius[2])
	
	YUV = core.std.ShufflePlanes([Yfix, Ufix, Vfix], [0,0,0], vs.YUV)
	
	return YUV
	
def ReferenceFixer(src, ref=None, left=[0,0,0], top=[0,0,0], right=[0,0,0], bottom=[0,0,0], radius=[0,0,0]):
	core = vs.core
	
	if ref is None:
		refc = core.std.BoxBlur(src, hradius=2, hpasses=2, vradius=2, vpasses=2)
	else:
		refc = ref
	
	Y = core.std.ShufflePlanes(src, [0], vs.GRAY)
	U = core.std.ShufflePlanes(src, [1], vs.GRAY)
	V = core.std.ShufflePlanes(src, [2], vs.GRAY)
	
	Yref = core.std.ShufflePlanes(refc, [0], vs.GRAY)
	Uref = core.std.ShufflePlanes(refc, [1], vs.GRAY)
	Vref = core.std.ShufflePlanes(refc, [2], vs.GRAY)
	
	if (left[0] + top[0] + right[0] + bottom[0] > 0):
		Yfix = core.edgefixer.Reference(Y, Yref, left[0], top[0], right[0], bottom[0], radius[0])
		
	if (left[1] + top[1] + right[1] + bottom[1] > 0):
		Ufix = core.edgefixer.Reference(U, Uref, left[1], top[1], right[1], bottom[1], radius[1])
		
	if (left[2] + top[2] + right[2] + bottom[2] > 0):
		Vfix = core.edgefixer.Reference(V, Vref, left[2], top[2], right[2], bottom[2], radius[2])
	
	YUV = core.std.ShufflePlanes([Yfix, Ufix, Vfix], [0,0,0], vs.YUV)
	
	return YUV
```

**Comment by JustinTArthur** [comment]
I'll give vsfieldkit an edgefixer.* option, though @MonoS your fork is still more widely used as @sekrit-twc's only has a Microsoft Windows build.

**Comment by MonoS** [comment]
Hi @JustinTArthur, neither my fork has other than windows build, maybe it's simpler to build but i've never released Linux/Mac build.
Anyway, i've compiled the new build, hope you'll find it useful :)

**Comment by JustinTArthur** [comment]
> neither my fork has other than windows build

Maybe not, but your README instructions are cross-platform as long as you replace ".dll" with ".so" or ".dylib" accordingly. Building the @sekrit-twc branch isn't bad on the other platforms either, but is completely manual and without instruction at the moment.

> Anyway, i've compiled the new build, hope you'll find it useful :)

That's great. Thank you! The new syntax [had already been featured in the popular mdbook](https://silentaperture.gitlab.io/mdbook-guide/filtering/dirty_lines.html#continuityfixer). I suspect many were building from HEAD.
